// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlUUzu8IutR4D7SFV-mrb_m3ABLnH_QUo',
    appId: '1:117469352882:web:24aa151d9c34316d5e8aab',
    messagingSenderId: '117469352882',
    projectId: 'tuwulireapp',
    authDomain: 'tuwulireapp.firebaseapp.com',
    storageBucket: 'tuwulireapp.appspot.com',
    measurementId: 'G-S561S3ZHHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB73LYpsiCq-1_he4DY7FWHDq7y3pKoRj8',
    appId: '1:117469352882:android:5238cfdab495a1ea5e8aab',
    messagingSenderId: '117469352882',
    projectId: 'tuwulireapp',
    storageBucket: 'tuwulireapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8-0w6PrZi0VkLDdU1bD2DiT4yiB9X4-o',
    appId: '1:117469352882:ios:cd2cd7e2446a23605e8aab',
    messagingSenderId: '117469352882',
    projectId: 'tuwulireapp',
    storageBucket: 'tuwulireapp.appspot.com',
    iosClientId: '117469352882-g0i54i44b40sula9fvsbl7bf5vko1441.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuwulire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8-0w6PrZi0VkLDdU1bD2DiT4yiB9X4-o',
    appId: '1:117469352882:ios:cd2cd7e2446a23605e8aab',
    messagingSenderId: '117469352882',
    projectId: 'tuwulireapp',
    storageBucket: 'tuwulireapp.appspot.com',
    iosClientId: '117469352882-g0i54i44b40sula9fvsbl7bf5vko1441.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuwulire',
  );
}
